/**
 * gen-progress — concatenate per-agent heartbeats into PROGRESS.md.
 *
 * Why this exists: see docs/heartbeats/README.md. Eliminates the
 * PROGRESS.md merge-collision pattern by giving each agent its own
 * append-only file and regenerating PROGRESS.md from those files.
 *
 *   pnpm gen:progress          # update PROGRESS.md in place
 *   pnpm gen:progress:check    # exit 1 if PROGRESS.md is out of date (CI)
 *
 * Behaviour
 *   - Globs `docs/heartbeats/track-{a,b}/*.md` (ignores README + .gitkeep).
 *   - Sorts by filename DESCENDING (newest date first).
 *   - For each file: emits a "## YYYY-MM-DD · Track X" header + the file's
 *     bullets verbatim.
 *   - Writes the result between the markers
 *       <!-- BEGIN AGENT HEARTBEATS - generated by scripts/gen-progress.ts -->
 *       <!-- END AGENT HEARTBEATS -->
 *     in PROGRESS.md. Everything OUTSIDE the markers is preserved byte-for-byte.
 *   - `--check`: compute what the file SHOULD look like; exit 1 if it differs.
 *
 * Same posture as apps/api/scripts/gen-api-docs.ts:
 *   - Deterministic (stable sort, no timestamps in the output).
 *   - Idempotent (running twice without source changes is a no-op).
 *   - Comparison is byte-exact for the --check path.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const HEARTBEATS_DIR = join(ROOT, 'docs', 'heartbeats');
const PROGRESS_FILE = join(ROOT, 'PROGRESS.md');

const BEGIN = '<!-- BEGIN AGENT HEARTBEATS - generated by scripts/gen-progress.ts -->';
const END = '<!-- END AGENT HEARTBEATS -->';

const TRACK_LABELS: Record<string, string> = {
  'track-a': 'Track A · Design Re-skin (FE)',
  'track-b': 'Track B · BE Specialist',
  // Future tracks: add here.
};

interface HeartbeatFile {
  track: string;
  date: string; // YYYY-MM-DD
  path: string;
  content: string;
}

function collect(): HeartbeatFile[] {
  if (!existsSync(HEARTBEATS_DIR)) return [];
  const tracks = readdirSync(HEARTBEATS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name.startsWith('track-'))
    .map((d) => d.name);

  const out: HeartbeatFile[] = [];
  for (const track of tracks) {
    const trackDir = join(HEARTBEATS_DIR, track);
    const files = readdirSync(trackDir, { withFileTypes: true })
      .filter((f) => f.isFile() && f.name.endsWith('.md'))
      // README.md belongs at the parent level, not here, but skip defensively.
      .filter((f) => f.name !== 'README.md');
    for (const f of files) {
      const date = basename(f.name, '.md');
      // Validate YYYY-MM-DD shape — anything else is a typo we should
      // surface as a CI failure, not silently ignore.
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        throw new Error(
          `gen-progress: invalid heartbeat filename "${f.name}" in ${trackDir} — must be YYYY-MM-DD.md`,
        );
      }
      out.push({
        track,
        date,
        path: join(trackDir, f.name),
        content: readFileSync(join(trackDir, f.name), 'utf8').trim(),
      });
    }
  }
  return out;
}

function render(files: HeartbeatFile[]): string {
  if (files.length === 0) {
    return `${BEGIN}\n_(no agent heartbeats yet — write to \`docs/heartbeats/track-<your-track>/<today>.md\` and re-run \`pnpm gen:progress\`)_\n${END}`;
  }
  // Sort: newest date first; within same date, alphabetical track for stability.
  files.sort((a, b) => {
    if (a.date !== b.date) return b.date.localeCompare(a.date);
    return a.track.localeCompare(b.track);
  });
  const sections = files.map((f) => {
    const label = TRACK_LABELS[f.track] ?? f.track;
    return `### ${f.date} · ${label}\n\n${f.content}`;
  });
  return `${BEGIN}\n${sections.join('\n\n')}\n${END}`;
}

function splice(progress: string, generated: string): string {
  const beginIdx = progress.indexOf(BEGIN);
  const endIdx = progress.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `gen-progress: PROGRESS.md must contain both markers (${BEGIN} ... ${END}). Place them where you want the auto-generated heartbeats to appear.`,
    );
  }
  // Replace begin..end (inclusive of END marker length).
  const before = progress.slice(0, beginIdx);
  const after = progress.slice(endIdx + END.length);
  return `${before}${generated}${after}`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const files = collect();
  const generated = render(files);
  const current = readFileSync(PROGRESS_FILE, 'utf8');
  const next = splice(current, generated);

  if (check) {
    if (next !== current) {
      process.stderr.write(
        'gen-progress: PROGRESS.md is OUT OF DATE relative to docs/heartbeats/.\n' +
          'Run `pnpm gen:progress` and commit the result.\n',
      );
      process.exit(1);
    }
    process.stdout.write('PROGRESS.md up to date.\n');
    return;
  }

  writeFileSync(PROGRESS_FILE, next, 'utf8');
  process.stdout.write(
    `gen-progress: wrote ${files.length} heartbeat entr${files.length === 1 ? 'y' : 'ies'} into PROGRESS.md.\n`,
  );
}

main();
